db_path: stocktracker.db
csv_path: import.csv

# Logging configuration
log_config_path: config/logging_config.yaml
log_file_path: app.log
log_level: DEBUG

# Yahoo Finance rate limit (requests per X seconds)
yf_max_requests: 1
yf_request_interval_seconds: 5
yf_cache_path: yfinance.cache
yf_cache_expiry: 3600
