version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: "[%(asctime)s] %(levelname)s: %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: tickers.log
    mode: a

loggers:
  tickers:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  db:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  refresh_splits:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console]
